env: "local"
http_server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 30s

ujin:
  api_url: "https://api-uae-test.ujin.tech"
  user_token: "ust-738975-7546d637ccea657af49f1eeecd9e4806"
  admin_token: "ust-739005-c8bb190f92541a2c1e839b98cbc469c9"