version: '3.9'

services:
  database:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_DB=hackathon
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      some_network:

  webapi:
    image: webapi
    build: backend/
    depends_on:
      database:
        condition: service_healthy
    command: ./hackathon-digital-construction-2023
    networks:
      some_network:
    environment:
      IS_CONTAINER: true
      CONFIG_PATH: /app/config/local.yaml

  nginx:
    build: frontend/
    ports:
      - "80:80"
    depends_on:
      - webapi
    networks:
      some_network:


networks:
  some_network:
    name: 'some_network'
